### ISSUE TITLE
Allow disabling of notification

### ISSUE THREAD

**Issue by jas99** [EternalPhane/tsfmt-vscode#1]
Hey @EternalPhane 
Awesome extension!!

Can you please provide option to disable error notification in extension options.

Thx

**Comment by jas99** [comment]
Hey @EternalPhane 
Thx for taking time out and introducing feature
But I checkout; when I set notification to disabled; its still appearing for me.

I think doing following might help

`return workspace.getConfiguration('tsfmt').get('notification') || true;`
to
`return workspace.getConfiguration('tsfmt').get('notification') && true;`

**Comment by EternalPhane** [comment]
@jas99 sry I was too busy to correct it given that final exam is coming and I still have some assignments to finish. please try it again. I believe it's fixed this time.
